app:
  base-url: ${APP_BASE_URL:http://localhost:${APP_PORT:8080}}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  mail:
    from:
      address: ${MAIL_USERNAME}
      name: HireMe App

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/eureka/}

spring:
  application:
    name: AuthService
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  jwt:
    secret: ${JWT_SECRET:7a45678901234567890123456789012345678901234567890123456789012345}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS:true}
            required: ${MAIL_STARTTLS:true}
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

server:
  port: ${APP_PORT}
  servlet:
    context-path: /api

# Swagger/OpenAPI Configuration
springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    enabled: true

  # Swagger UI Configuration
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
