app:
  base-url: ${APP_BASE_URL:http://localhost:${APP_PORT:8080}}
  mail:
    from:
        address: ${MAIL_USERNAME}
        name: HireMe App

spring:
  application:
    name: AuthService
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop

  jwt:
    secret: ${JWT_SECRET:7a45678901234567890123456789012345678901234567890123456789012345}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

server:
  port: ${APP_PORT}
  servlet:
    context-path: /api
    
# Swagger/OpenAPI Configuration
springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    enabled: true
  
  # Swagger UI Configuration
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
