spring:
  application:
    name: AuthService
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/auth
    
# Swagger/OpenAPI Configuration
springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    enabled: true
  
  # Swagger UI Configuration
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
