spring:
  application:
    name: MatchingService
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: matching-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.hireme.matchingservice.events.UserDeletedEvent
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"

server:
  port: ${APP_PORT:8084}
  servlet:
    context-path: /api

ml-engine:
  base-url: ${ML_ENGINE_URL:http://ml-engine:8000}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/eureka/}

springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
