services:
  db:
    image: postgres:17-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mail-server:
    image: axllent/mailpit
    container_name: auth-mail
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - PG_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - PG_USERNAME=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_AUTH=${MAIL_AUTH}
      - MAIL_STARTTLS=${MAIL_STARTTLS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
