spring:
  application:
    name: JobService
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: ${APP_PORT:8083}
  servlet:
    context-path: /api

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/eureka/}

springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
