spring:
  application:
    name: Gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**

            - id: resume-service
              uri: http://resume-service:8082
              predicates:
                - Path=/api/resumes/**, /api/contacts/**, /api/educations/**, /api/experiences/**, /api/skills/**, /api/languages/**, /api/templates/**

server:
  port: ${GATEWAY_PORT:-8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
